// AUTO-GENERATED by AI image generation pipeline
// Maps biome key → Phaser texture key for AI-generated terrain tiles
// Used by BiomeTileRenderer to overlay terrain texture onto tile faces

export const BIOME_AI_TILES = {
  corrupt_swamp: { key: 'tile_corrupt_swamp', path: 'assets/tiles/corrupt_swamp.png', name: '腐化沼泽' },
  crystal_caves: { key: 'tile_crystal_caves', path: 'assets/tiles/crystal_caves.png', name: '水晶洞穴' },
  lava_plateau: { key: 'tile_lava_plateau', path: 'assets/tiles/lava_plateau.png', name: '熔岩高原' },
  aurora_tundra: { key: 'tile_aurora_tundra', path: 'assets/tiles/aurora_tundra.png', name: '极光冻原' },
  ghost_bay: { key: 'tile_ghost_bay', path: 'assets/tiles/ghost_bay.png', name: '幽灵海湾' },
  toxic_jungle: { key: 'tile_toxic_jungle', path: 'assets/tiles/toxic_jungle.png', name: '毒素丛林' },
  ash_desert: { key: 'tile_ash_desert', path: 'assets/tiles/ash_desert.png', name: '骨灰荒漠' },
  rusted_ruins: { key: 'tile_rusted_ruins', path: 'assets/tiles/rusted_ruins.png', name: '废铁遗迹' },
  meteor_crater: { key: 'tile_meteor_crater', path: 'assets/tiles/meteor_crater.png', name: '陨石荒地' },
  abyss_rift: { key: 'tile_abyss_rift', path: 'assets/tiles/abyss_rift.png', name: '深渊裂缝' },
  mushroom_forest: { key: 'tile_mushroom_forest', path: 'assets/tiles/mushroom_forest.png', name: '巨菇密林' },
  mirage_oasis: { key: 'tile_mirage_oasis', path: 'assets/tiles/mirage_oasis.png', name: '幻境绿洲' },
  silver_peaks: { key: 'tile_silver_peaks', path: 'assets/tiles/silver_peaks.png', name: '银雪山脉' },
  decay_forest: { key: 'tile_decay_forest', path: 'assets/tiles/decay_forest.png', name: '腐朽密林' },
  chaos_forge: { key: 'tile_chaos_forge', path: 'assets/tiles/chaos_forge.png', name: '混沌熔炉' },
}

// Preload helper — call from scene.preload()
export function preloadBiomeTiles(scene) {
  for (const [, cfg] of Object.entries(BIOME_AI_TILES)) {
    scene.load.image(cfg.key, cfg.path)
  }
}

// BIOME ID → tile key mapping (matches BIOME constants 6-20)
export const BIOME_ID_TO_TILE_KEY = {
  6:  'tile_corrupt_swamp',
  7:  'tile_crystal_caves',
  8:  'tile_lava_plateau',
  9:  'tile_aurora_tundra',
  10: 'tile_ghost_bay',
  11: 'tile_toxic_jungle',
  12: 'tile_ash_desert',
  13: 'tile_rusted_ruins',
  14: 'tile_meteor_crater',
  15: 'tile_abyss_rift',
  16: 'tile_mushroom_forest',
  17: 'tile_mirage_oasis',
  18: 'tile_silver_peaks',
  19: 'tile_decay_forest',
  20: 'tile_chaos_forge',
}
